# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class PerlPerlCriticPulp(PerlPackage):
    """Some add-on policies for Perl::Critic."""

    homepage = "http://user42.tuxfamily.org/perl-critic-pulp/index.html"
    url = "https://cpan.metacpan.org/authors/id/K/KR/KRYDE/Perl-Critic-Pulp-99.tar.gz"

    license("GPL-3.0-or-later", checked_by="greenc-FNAL")

    maintainers("gartung", "greenc-FNAL", "marcmengel")

    version("99", sha256="b8fda842fcbed74d210257c0a284b6dc7b1d0554a47a3de5d97e7d542e23e7fe")
    version("98", sha256="476f00aea58ca8a10a09ff709e90506ddb70ae35f6574ae184e08eb944413da0")

    provides("perl-perl-critic-podparser-prohibitverbatimmarkup")
    provides("perl-perl-critic-policy-codelayout-prohibitfatcommanewline")
    provides("perl-perl-critic-policy-codelayout-prohibitififsameline")
    provides("perl-perl-critic-policy-codelayout-requirefinalsemicolon")
    provides("perl-perl-critic-policy-codelayout-requiretrailingcommaatnewline")
    provides("perl-perl-critic-policy-compatibility-constantleadingunderscore")
    provides("perl-perl-critic-policy-compatibility-constantpragmahash")
    provides("perl-perl-critic-policy-compatibility-gtk2constants")
    provides("perl-perl-critic-policy-compatibility-perlminimumversionandwhy")
    provides("perl-perl-critic-policy-compatibility-podminimumversion")
    provides("perl-perl-critic-policy-compatibility-prohibitunixdevnull")
    provides("perl-perl-critic-policy-documentation-prohibitadjacentlinks")
    provides("perl-perl-critic-policy-documentation-prohibitadjacentlinks-parser")
    provides("perl-perl-critic-policy-documentation-prohibitbadaproposmarkup")
    provides("perl-perl-critic-policy-documentation-prohibitduplicateheadings")
    provides("perl-perl-critic-policy-documentation-prohibitduplicateseealso")
    provides("perl-perl-critic-policy-documentation-prohibitlinktoself")
    provides("perl-perl-critic-policy-documentation-prohibitparagraphendcomma")
    provides("perl-perl-critic-policy-documentation-prohibitparagraphtwodots")
    provides("perl-perl-critic-policy-documentation-prohibitunbalancedparens")
    provides("perl-perl-critic-policy-documentation-prohibitverbatimmarkup")
    provides("perl-perl-critic-policy-documentation-requireendbeforelastpod")
    provides("perl-perl-critic-policy-documentation-requirefilenamemarkup")
    provides("perl-perl-critic-policy-documentation-requirefinalcut")
    provides("perl-perl-critic-policy-documentation-requirelinkedurls")
    provides("perl-perl-critic-policy-miscellanea-textdomainplaceholders")
    provides("perl-perl-critic-policy-miscellanea-textdomainunused")
    provides("perl-perl-critic-policy-modules-prohibitmoduleshebang")
    provides("perl-perl-critic-policy-modules-prohibitposiximport")
    provides("perl-perl-critic-policy-modules-prohibitusequotedversion")
    provides("perl-perl-critic-policy-valuesandexpressions-constantbeforelt")
    provides("perl-perl-critic-policy-valuesandexpressions-notwithcompare")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitarrayassignaref")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitbareworddoublecolon")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitduplicatehashkeys")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitemptycommas")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitfiletest-f")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitnullstatements")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitunknownbackslash")
    provides("perl-perl-critic-policy-valuesandexpressions-requirenumericversion")
    provides("perl-perl-critic-policy-valuesandexpressions-unexpandedspecialliteral")
    provides("perl-perl-critic-pulp-podminimumversionviolation")
    provides("perl-perl-critic-pulp-podparser")
    provides("perl-perl-critic-pulp-podparser-prohibitbadaproposmarkup")
    provides("perl-perl-critic-pulp-podparser-prohibitduplicateheadings")
    provides("perl-perl-critic-pulp-podparser-prohibitduplicateseealso")
    provides("perl-perl-critic-pulp-podparser-prohibitlinktoself")
    provides("perl-perl-critic-pulp-podparser-prohibitparagraphendcomma")
    provides("perl-perl-critic-pulp-podparser-prohibitparagraphtwodots")
    provides("perl-perl-critic-pulp-podparser-prohibitunbalancedparens")
    provides("perl-perl-critic-pulp-podparser-requirefilenamemarkup")
    provides("perl-perl-critic-pulp-podparser-requirefinalcut")
    provides("perl-perl-critic-pulp-podparser-requirelinkedurls")
    provides("perl-perl-critic-pulp-prohibitduplicatehashkeys-qword")
    provides("perl-perl-critic-pulp-utils")
    depends_on("perl-extutils-makemaker", type="build")
    depends_on("perl-io-string@1.2:", type="run")
    depends_on("perl-pod-minimumversion@50:", type="run")
    depends_on("perl-ppi@1.220:", type="run")
    depends_on("perl-perl-critic-violation", type="run")
    depends_on("perl-perl-critic@1.84:", type="run")
    depends_on("perl@5.6:", type="run")
    depends_on("perl-ppi-dumper", type="run")
    depends_on("perl-perl-critic-policy@1.84:", type="run")
    depends_on("perl-perl-critic-utils@1.100:", type="run")
    depends_on("perl-ppi-document", type="run")
    depends_on("perl-list-moreutils@0.24:", type="run")
    depends_on("perl-scalar-util", type="run")
    depends_on("perl-list-util", type="run")
    depends_on("perl-perl-critic-utils-ppi", type="run")
